# Generated by Django 5.2.4 on 2025-11-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0002_idempotencykeys_rating_buckets_card_reviews"),
    ]

    operations = [
        migrations.AlterField(
            model_name="card",
            name="next_review",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
