# Generated by Django 5.2.4 on 2025-11-13 21:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0003_alter_card_next_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rating_buckets",
            old_name="defaults",
            new_name="default_interval",
        ),
        migrations.RenameField(
            model_name="rating_buckets",
            old_name="ratings",
            new_name="score",
        ),
    ]
