# Generated by Django 5.2.4 on 2025-11-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0004_rename_defaults_rating_buckets_default_interval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="ratings",
        ),
        migrations.AddField(
            model_name="card",
            name="ease",
            field=models.FloatField(default=2.5),
        ),
        migrations.AddField(
            model_name="card",
            name="interval",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reviews",
            name="ratingScore",
            field=models.IntegerField(
                choices=[(0, "Again"), (1, "Good"), (2, "Easy")], default=1
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Rating_Buckets",
        ),
    ]
