# Generated by Django 5.2.4 on 2025-11-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0005_remove_reviews_ratings_card_ease_card_interval_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="continuous_recall",
            new_name="step",
        ),
        migrations.AddField(
            model_name="card",
            name="state",
            field=models.CharField(
                choices=[
                    ("learning", "Learning"),
                    ("reviewing", "Reviewing"),
                    ("relearning", "Relearning"),
                ],
                default="learning",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="ratingScore",
            field=models.IntegerField(choices=[(0, "Again"), (1, "Hard"), (2, "Easy")]),
        ),
    ]
