# Generated by Django 5.2.4 on 2025-11-16 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0006_rename_continuous_recall_card_step_card_state_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="interval",
        ),
    ]
