# Generated by Django 5.2.4 on 2025-11-16 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assignment", "0007_remove_card_interval"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="interval",
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
